version: '3.9'

services:
  loki:
    image: grafana/loki:3.1.1
    command: ["-config.file=/etc/loki/config/loki-config.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki/config
      - ./data/loki:/loki

  promtail:
    image: grafana/promtail:3.1.1
    command: ["--config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ../../logs:/var/log/analytics:ro
      - ./data/positions:/tmp
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - loki
